In [9]:
def square(a = 2):
    """ hii function inasquare number yoyote utakayo ipa
    example usage:
    num = square(2)
    print(num)
    4
    """
    return a*a

In [10]:
square()

4

In [8]:
range(0,10,2)

range(0, 10, 2)

In [18]:
num = [[1,2,3],[4,5,6]]

In [20]:
num

[[1, 2, 3], [4, 5, 6]]

In [23]:
num[:][1]

[4, 5, 6]

In [1]:
2

2

In [2]:
[2,3]

[2, 3]

In [3]:
[[2,3],[3,4]]

[[2, 3], [3, 4]]

In [4]:
A = 5
b = A

In [5]:
import numpy as np

In [13]:
arr = np.arange(0,3)

In [14]:
arr

array([0, 1, 2])

In [15]:
arr2 = arr.copy()

In [16]:
arr2

array([0, 1, 2])

In [17]:
arr2[0] = 9

In [18]:
arr

array([0, 1, 2])

In [19]:
arr2

array([9, 1, 2])